import PDFDocument from "pdfkit";

export const generatePdf = async (data) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
      info: {
        Author: "IgrisAI",
        Title: data.title,
        Creator: "IgrisAI",
      },
    });
    const chunks = [];

    doc.on("data", (chunk) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // title
    doc
      .fontSize(28)
      .fillColor("#111827")
      .text(data.title, {
        align: "center",
      });
    if (data.subtitle) {
      doc.moveDown(0.5);
      doc
        .fontSize(12)
        .fillColor("#687280")
        .text(data.subtitle, {
          align: "center",
        });
    }

    doc.moveDown(2);

    // sections

    data?.sections?.forEach((s) => {
      doc
        .fontSize(18)
        .fillColor("#111827")
        .text(s.heading, {
          align: "center",
        });
      doc.moveDown(0.5);

      s?.points?.forEach((p) => {
        doc
          .fontSize(12)
          .fillColor("#374151")
          .text(`• ${p}`, {
            lineGap: 5,
          });
        doc.moveDown(0.5);
      });
    });

    // footer
    doc.moveDown();

    doc
      .fontSize(10)
      .fillColor("#9CA3AF")
      .text("Generated by IgrisAI", {
        align: "center",
      });

    doc.end();
  });
};
